### ISSUE TITLE
Install fails on OS X due to fibers dependency

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#1132]
`npm install` fails for me on Yosemite

```
$ npm -v
3.4.0
$ node -v
v0.12.7
```

this was after removing `node_modules` and doing a fresh install. When I try and install it explicitly I get the following:

```
$ npm install fibers

> fibers@1.0.8 install /Users/cjm/repos/monarch-app/node_modules/fibers
> node build.js || nodejs build.js

2015-12-20 16:34:09.178 xcodebuild[12292:460355] Error loading /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Xcode/PrivatePlugIns/iPhoneOS Build System Support.xcplugin/Contents/MacOS/iPhoneOS Build System Support:  dlopen(/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Xcode/PrivatePlugIns/iPhoneOS Build System Support.xcplugin/Contents/MacOS/iPhoneOS Build System Support, 265): Library not loaded: /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice
  Referenced from: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/PrivateFrameworks/DTDeviceKitBase.framework/Versions/A/DTDeviceKitBase
  Reason: no suitable image found.  Did find:
        /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice: GC capability mismatch
2015-12-20 16:34:09.179 xcodebuild[12292:460355] WARNING: Failed to load plugin at: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Xcode/PrivatePlugIns/iP
honeOS Build System Support.xcplugin, skipping.  Could not load bundle.
  CXX(target) Release/obj.target/fibers/src/fibers.o
In file included from ../src/fibers.cc:1:
In file included from ../src/coroutine.h:1:
In file included from /Users/cjm/.node-gyp/0.12.7/src/node.h:61:
In file included from /Users/cjm/.node-gyp/0.12.7/deps/v8/include/v8.h:18:
/Users/cjm/.node-gyp/0.12.7/deps/v8/include/v8stdint.h:11:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^
1 error generated.
make: *** [Release/obj.target/fibers/src/fibers.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /Users/cjm/repos/monarch-app/node_modules/fibers
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
Build failed
sh: nodejs: command not found
npm ERR! Darwin 15.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "fibers"
npm ERR! node v0.12.7
npm ERR! npm  v3.4.0
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! fibers@1.0.8 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
```

Why do we need fibers anyway? We shouldn't be doing anything that requires threading in the monarch app.

**Comment by cmungall** [comment]
Looks like an Xcode issue. Ah, feels like another century tracing down odd C compiler linker errors
