### ISSUE TITLE
node-server throws error in beta environment

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#938]
https://build.berkeleybop.org/view/Monarch/job/start-monarch-server

```
$ cat server.err 

module.js:340
    throw err;
          ^
Error: Cannot find module '/lib/monarch/web/webapp_launcher_node.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
Using pre-set configuration: 
Using pre-set golr configuration: 
This is a development server
```

**Comment by cmungall** [comment]
I believe this is because we start up like this

```
BUILD_ID=dontKillMe  /usr/sbin/daemonize -v -e $PWD/server.err -o $PWD/server.out -p $PWD/server.pid $PWD/node-server.sh
```

node-server.sh:

```
NODE_PATH=./lib/monarch node lib/monarch/web/webapp_launcher_node.js
```

`.` is no longer the current dir

**Comment by cmungall** [comment]
There's some obvious fixes just a bit lacking in bandwidth now

**Comment by cmungall** [comment]
Very annoying... I hate daemonize

```
+ /usr/sbin/daemonize -v -E NODE_PATH=/var/home/jenkins-slave/workspace/start-monarch-server/lib/monarch -e /var/home/jenkins-slave/workspace/start-monarch-server/server.err -o /var/home/jenkins-slave/workspace/start-monarch-server/server.out -p /var/home/jenkins-slave/workspace/start-monarch-server/server.pid /var/home/jenkins-slave/workspace/start-monarch-server/node-server-beta.sh
+ sleep 25

+ cat server.pid
59282
+ cat server.err

module.js:340
    throw err;
          ^
Error: Cannot find module '/lib/monarch/web/webapp_launcher_node.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```

**Comment by cmungall** [comment]
@kshefchek can you coordinate with Larry and @DoctorBud to get this done, @kltm and I are out of town til late next week

**Comment by kshefchek** [comment]
Looking at the build in bamboo I believe this has been fixed, @cmungall please reopen if not.
