### ISSUE TITLE
Problems deploying monarch app on stage (nodejs?)

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#977]
Moving this from JIRA. @DoctorBud @kshefchek @kltm any ideas?

Log file here:
https://bamboo.crbs.ucsd.edu/download/MON-STMONARCH-JOB1/build_logs/MON-STMONARCH-JOB1-81.log

```
    [ https://support.crbs.ucsd.edu/browse/CRBS-10581?page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel&focusedCommentId=137312#comment-137312 ]

Larry Lui commented on CRBS-10581:
----------------------------------

Looking at the logs here:
https://bamboo.crbs.ucsd.edu/download/MON-STMONARCH-JOB1/build_logs/MON-STMONARCH-JOB1-81.log

Looks like there were some errors with some of the dependencies.  Starts here in the logs:
build   30-Sep-2015 14:29:32      CXX(target) Release/obj.target/validation/src/validation.o



Looks like

Problem with MON-STMONARCH-JOB
------------------------------

                Key: CRBS-10581
                URL: https://support.crbs.ucsd.edu/browse/CRBS-10581
            Project: CRBS Support
         Issue Type: Task
           Reporter: Chris Mungall
           Assignee: Sean Penticoff

Hi,
I'm trying a test deployment of the monarch app on stage, and I get an
error message involving sudo:
https://bamboo.crbs.ucsd.edu/browse/MON-STMONARCH-JOB1-80/log



--
This message was sent by Atlassian JIRA
(v6.3.1#6329)
```

**Comment by cmungall** [comment]
Do we need to worry about this?

```
uild    30-Sep-2015 14:30:29    > bufferutil@1.2.1 install /var/home/bamboo/start-monarch-server/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
build   30-Sep-2015 14:30:29    > node-gyp rebuild
build   30-Sep-2015 14:30:29    
build   30-Sep-2015 14:30:30    make: Entering directory `/var/home/bamboo/start-monarch-server/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil/build'
build   30-Sep-2015 14:30:30      CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
error   30-Sep-2015 14:30:30    In file included from ../src/bufferutil.cc:16:
error   30-Sep-2015 14:30:30    ../node_modules/nan/nan.h:316: error: ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’
build   30-Sep-2015 14:30:31    make: Leaving directory `/var/home/bamboo/start-monarch-server/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil/build'
error   30-Sep-2015 14:30:31    make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
error   30-Sep-2015 14:30:31    gyp ERR! build error 
error   30-Sep-2015 14:30:31    gyp ERR! stack Error: `make` failed with exit code: 2
error   30-Sep-2015 14:30:31    gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:267:23)
error   30-Sep-2015 14:30:31    gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
error   30-Sep-2015 14:30:31    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
error   30-Sep-2015 14:30:31    gyp ERR! System Linux 2.6.32-358.el6.x86_64
error   30-Sep-2015 14:30:31    gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
error   30-Sep-2015 14:30:31    gyp ERR! cwd /var/home/bamboo/start-monarch-server/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
error   30-Sep-2015 14:30:31    gyp ERR! node -v v0.10.36
error   30-Sep-2015 14:30:31    gyp ERR! node-gyp -v v0.10.6
error   30-Sep-2015 14:30:31    gyp ERR! not ok 
error   30-Sep-2015 14:30:31    npm WARN optional dep failed, continuing bufferutil@1.2.1
build   30-Sep-2015 14:30:31    
```
